version: '3'
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 3000:80
    links:
      - mysql:db
    depends_on:
      - mysql
    container_name: numeris_phpmyadmin

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'numeris'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: numeris_mysql

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: numeris
      DB_USERNAME: root
      DB_PASSWORD:
    volumes:
      - ./back:/home/numeris
      - /home/numeris/vendor
    ports:
      - ${BACK_PORT:-8000}:80
    links:
      - mysql
    depends_on:
      - mysql
    container_name: numeris_back

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/src:/home/numeris/src
      - /home/numeris/node_modules
    links:
      - back
    ports:
      - ${FRONT_PORT:-8080}:80
    command: ng s --host 0.0.0.0
    container_name: numeris_front
