version: '3'
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: numeris_phpmyadmin
    restart: unless-stopped
    ports:
      - 3000:80
    links:
      - mysql:db
    depends_on:
      - mysql
    volumes:
      - ./var/mysql_testing:/var/lib/mysql

  mysql:
    image: mysql:5.7
    container_name: numeris_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'numeris_testing'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  back:
    container_name: numeris_back
    restart: unless-stopped
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: testing
      DB_HOST_TESTING: mysql
      DB_PORT_TESTING: 3306
      DB_DATABASE_TESTING: numeris_testing
      DB_USERNAME_TESTING: root
      DB_PASSWORD_TESTING:
    ports:
      - 8080:80
    links:
      - mysql
    depends_on:
      - mysql

  front:
    container_name: numeris_front
    restart: unless-stopped
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    links:
      - back
    depends_on:
      - back
