version: "3.9"
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 3000:80
    links:
      - mysql:db
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'numeris'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  back:
    image: numerisisep/back:dev
    container_name: numeris_back
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - ./back/.env
    environment:
      DB_HOST: ${DB_HOST:-mysql}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-numeris}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./back:/home/numeris
      - /home/numeris/vendor
    ports:
      - ${BACK_PORT:-8000}:80
    links:
      - mysql
    depends_on:
      - mysql

  front:
    image: numerisisep/front:dev
    container_name: numeris_front
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/src:/home/numeris/src
      - /home/numeris/node_modules
    ports:
      - ${FRONT_PORT:-5000}:${FRONT_PORT:-5000}
    command: ng serve --host 0.0.0.0
