version: '3'
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 3000:80
    links:
      - mysql:db
    depends_on:
      - mysql
    container_name: numeris_phpmyadmin

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'numeris'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: numeris_mysql

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - back/.env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./back:/home/numeris
      - /home/numeris/vendor
    ports:
      - ${BACK_PORT}:80
    links:
      - mysql
    depends_on:
      - mysql
    container_name: numeris_back

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/src:/home/numeris/src
      - /home/numeris/node_modules
    links:
      - back
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    command: ng s --host 0.0.0.0
    container_name: numeris_front
