version: "3.9"
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 3000:80
    links:
      - mysql:db
    depends_on:
      - mysql
    container_name: numeris_phpmyadmin

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: 'numeris'
    volumes:
    - ./var/mysql:/var/lib/mysql
    container_name: numeris_mysql

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${BACK_PORT}:80
    links:
    - mysql
    depends_on:
    - mysql
    container_name: numeris_back
