version: "3.9"
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: numeris_phpmyadmin
    restart: unless-stopped
    ports:
      - 3000:80
    links:
      - mysql:db
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: numeris_mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
    - ./var/mysql:/var/lib/mysql

  back:
    container_name: numeris_back
    restart: unless-stopped
    build:
      context: ./back
      dockerfile: Dockerfile.production
    env_file:
      - .env
    depends_on:
    - mysql

  front:
    container_name: numeris_front
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - back

volumes:
  mysql:
