name: Test build

on:
  push:
    branches:
      - "*"
      - "!master"
      - "!staging"
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  back-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Fake env file
      run: touch .env

    - name: Build
      run: docker-compose -f docker-compose.infra.yml build back

  front-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Fake env file
      run: touch .env

    - name: Build
      run: docker-compose -f docker-compose.infra.yml build front

  back-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Fake env file
      run: touch .env

    - name: Build
      run: docker-compose -f docker-compose.yml build back

  front-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Fake env file
      run: touch .env

    - name: Build
      run: docker-compose -f docker-compose.yml build front
