name: Docker production

on:
  schedule:
  - cron: "0 4 * * 0" # run every sunday at 4 am to test if the image builds correctly given that changes of debian or compose packages can break the image
  push:
    branches:
      - "master"
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  build-front:
    name: Build front
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push front
      uses: docker/build-push-action@v3
      with:
        context: front
        dockerfile: Dockerfile
        push: true
        tags: numerisisep/numeris-front:latest

  build-back:
    name: Build back
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push back
      uses: docker/build-push-action@v3
      with:
        context: back
        dockerfile: Dockerfile.production
        push: true
        tags: numerisisep/numeris-back:latest


  pull-and-recreate:
    name: Pull and recreate
    needs:
      - build-front
      - build-back
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd numeris
          git pull
          docker-compose -f docker-compose.production.yml pull
          docker-compose -f docker-compose.production.yml up -d --force-recreate
