name: Docker build test

on:
  push:
    branches:
      - "*"
      - "!master"
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  build-back:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Fake env file
      run: touch .env

    - name: Build
      run: docker-compose -f docker-compose.production.yml build back

  build-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # - name: Fake env file
    #   run: touch .env

    - name: Build
      run: docker-compose -f docker-compose.production.yml build front
